# Generated by Django 3.2.2 on 2021-05-11 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categories_products', to='Shop.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_testimonials', to='Shop.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_testimonials', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
