# Generated by Django 3.2.2 on 2021-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20210516_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.FloatField(default=1, verbose_name='Cost'),
            preserve_default=False,
        ),
    ]
