# Generated by Django 3.2.2 on 2021-07-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_order_order_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-date_creating'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
