# Generated by Django 3.2.2 on 2021-05-11 08:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[225, 225], upload_to='../static/Shop/images', verbose_name='Image'),
        ),
    ]
