# Generated by Django 3.2.2 on 2021-07-16 11:13

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20210712_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='../static/Users/images/default-product-image.jpg', force_format=None, keep_meta=True, quality=0, size=[225, 225], upload_to='./static/Shop/images', verbose_name='Image'),
        ),
    ]
