# Generated by Django 3.2.2 on 2021-05-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('system_id', models.IntegerField(verbose_name='Id')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Carrency',
                'verbose_name_plural': 'Carrencies',
                'ordering': ['-date_creating'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=1, verbose_name='Cost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='stars_count',
            field=models.IntegerField(verbose_name='Stars'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currency_product', to='Shop.currency', verbose_name='Currency'),
        ),
    ]
